# Provider: Anthropic (native)
# Sourced by cc-use, never executed directly

unset ANTHROPIC_BASE_URL
unset ANTHROPIC_AUTH_TOKEN

export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY_REAL"

unset ANTHROPIC_DEFAULT_OPUS_MODEL
unset ANTHROPIC_DEFAULT_SONNET_MODEL
unset ANTHROPIC_DEFAULT_HAIKU_MODEL
unset CLAUDE_CODE_SUBAGENT_MODEL
